//
//  ToolsView.swift
//  WaterLogged
//
//  Created by John Meyer on 7/7/26.
//
//  Copyright © 2026 John Meyer.
//
//  This file is part of WaterLogged, a scuba dive logging application written by John Meyer.
//
//  WaterLogged is free software: you can redistribute it and/or modify it under the terms of the GNU
//  General Public License as published by the Free Software Foundation, either version 3 of the License,
//  or (at your option) any later version.
//
//  WaterLogged is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
//  even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
//  General Public License for more details.
//
//  You should have received a copy of the GNU General Public License along with WaterLogged. If not,
//  see <https://www.gnu.org/licenses/>.

import SwiftUI
import SwiftData
import UniformTypeIdentifiers

/// The single "Tools" destination: a responsive grid of tiles for the app's
/// utility and import actions. Each tile opens the existing tool interface as
/// a sheet (on macOS wide enough for the full forms); the UDDF tile launches
/// the system file picker directly, since UDDF import has no custom UI.
struct ToolsView: View {
	@Environment(\.modelContext) private var modelContext

	/// The tool currently presented as a sheet, if any.
	private enum ToolSheet: Identifiable {
		case bulkUpdate
		case backup
		case restore
		case diveComputer
		case exportUDDF

		var id: Self { self }
	}

	@State private var activeSheet: ToolSheet?
	@State private var showingUDDFImport = false
	@State private var uddfImportResult: UDDFImportResult?

	private let columns = [GridItem(.adaptive(minimum: 220), spacing: 16)]

	var body: some View {
		NavigationStack {
			ScrollView {
				LazyVGrid(columns: columns, spacing: 16) {
					ToolTile(
						title: "Import from Dive Computer",
						description: "Download dives from a Bluetooth-enabled dive computer.",
						systemImage: "badge.plus.radiowaves.forward"
					) { activeSheet = .diveComputer }

					ToolTile(
						title: "Bulk Updater",
						description: "Renumber dives, clean up stray data, and apply updates to a range of dives at once.",
						systemImage: "square.and.arrow.up.on.square"
					) { activeSheet = .bulkUpdate }

					ToolTile(
						title: "Export to UDDF",
						description: "Export your dives, sites, buddies, and more to a UDDF file. Due to limitations in "
						+ "the UDDF format, this tool does not support storing all of the data contained in "
						+ "WaterLogged. To create a complete backup of your data, use the Backup and Restore tools.",
						systemImage: "arrow.down.doc"
					) { activeSheet = .exportUDDF }

					ToolTile(
						title: "Import from UDDF",
						description: "Import data from a UDDF file exported by this or another app.",
						systemImage: "arrow.up.doc"
					) { showingUDDFImport = true }

					ToolTile(
						title: "Backup",
						description: "Save your entire log book to a single archive containing a UDDF file, an "
						+ "extras data file, and any saved media. Use this tool to save additional WaterLogged data "
						+ "such as photos, log book images, and lots of other data not supported by "
						+ "the UDDF format alone. This archive can be re-imported using the Restore tool.",
						systemImage: "clock.arrow.trianglehead.counterclockwise.rotate.90"
					) { activeSheet = .backup }

					ToolTile(
						title: "Restore",
						description: "Replace your log book with all of the data from an archive generated by the Backup tool.",
						systemImage: "clock.arrow.trianglehead.2.counterclockwise.rotate.90"
					) { activeSheet = .restore }
				}
				.padding()
			}
			.navigationTitle("Tools")
			.appGradientScrollBackground()
		}
		.sheet(item: $activeSheet) { sheet in
			toolSheet(sheet)
		}
		.fileImporter(
			isPresented: $showingUDDFImport,
			allowedContentTypes: [.uddf, .xml]
		) { result in
			switch result {
				case .success(let url):
					do {
						let summary = try UDDFImporter.importFile(at: url, into: modelContext)
						uddfImportResult = .success(summary)
					} catch {
						uddfImportResult = .failure(error.localizedDescription)
					}
				case .failure(let error):
					uddfImportResult = .failure(error.localizedDescription)
			}
		}
		.alert(uddfImportResult?.title ?? "", item: $uddfImportResult) { _ in
			Button("OK") { }
		} message: { result in
			Text(result.message)
		}
	}

	@ViewBuilder
	private func toolSheet(_ sheet: ToolSheet) -> some View {
		Group {
			switch sheet {
				case .bulkUpdate: BulkUpdateView(presentation: .sheet)
				case .backup: BackupToolView(presentation: .sheet)
				case .restore: RestoreToolView(presentation: .sheet)
				case .diveComputer: DiveComputerView()
				case .exportUDDF: UDDFExportToolView(presentation: .sheet)
			}
		}
#if os(macOS)
		.frame(minWidth: 700)
#endif
	}
}

#Preview {
	ToolsView()
		.modelContainer(PreviewContainer.container)
}
